// <auto-generated />
using System;
using BooksApp.Data.Concrete.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksApp.Data.Migrations
{
    [DbContext(typeof(BooksAppContext))]
    [Migration("20230424131055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("BooksApp.Entity.Concrete.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3434),
                            Gender = "E",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3449),
                            Name = "Orhan Parasaçan",
                            Url = "orhan-parasacan"
                        },
                        new
                        {
                            Id = 2,
                            About = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3454),
                            Gender = "E",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3455),
                            Name = "Selami Gülgeçen",
                            Url = "selami-gulgecen"
                        },
                        new
                        {
                            Id = 3,
                            About = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3458),
                            Gender = "E",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3459),
                            Name = "Seyhan Yolagelen",
                            Url = "seyhan-yolagelen"
                        },
                        new
                        {
                            Id = 4,
                            About = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3461),
                            Gender = "E",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3462),
                            Name = "Hale Çokseven",
                            Url = "hale-cokseven"
                        },
                        new
                        {
                            Id = 5,
                            About = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3464),
                            Gender = "E",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3465),
                            Name = "Kemal Devabulan",
                            Url = "kemal-devabulan"
                        },
                        new
                        {
                            Id = 6,
                            About = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3467),
                            Gender = "E",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 807, DateTimeKind.Local).AddTicks(3468),
                            Name = "Selen Günebakan",
                            Url = "selen-gunebakan"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditionNumber")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EditionYear")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Stock")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2517),
                            EditionNumber = 1,
                            EditionYear = 2020,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2529),
                            Name = "Fahrenheit 451",
                            PageCount = 150,
                            Price = 75m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "fahrenheit-451"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2540),
                            EditionNumber = 43,
                            EditionYear = 2010,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2541),
                            Name = "Kadınlar Ülkesi",
                            PageCount = 120,
                            Price = 175m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "kadinlar-ulkesi"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2546),
                            EditionNumber = 13,
                            EditionYear = 2010,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2547),
                            Name = "İnsanlar",
                            PageCount = 180,
                            Price = 705m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "insanlar"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2551),
                            EditionNumber = 2,
                            EditionYear = 2022,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2552),
                            Name = "Görünmez Adam",
                            PageCount = 190,
                            Price = 15m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "gorunmez-adam"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2556),
                            EditionNumber = 13,
                            EditionYear = 2018,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2556),
                            Name = "Siyah Günce",
                            PageCount = 250,
                            Price = 47m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "siyah-gunce"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2560),
                            EditionNumber = 8,
                            EditionYear = 2016,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2561),
                            Name = "Nebo'nun Mavi Kitabı",
                            PageCount = 50,
                            Price = 68m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "nebonun-mavi-kitabi"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2565),
                            EditionNumber = 7,
                            EditionYear = 2021,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2566),
                            Name = "Evrenin Sonundaki Restoran",
                            PageCount = 15,
                            Price = 114m,
                            Stock = 0,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "evrenin-sonundaki-restoran"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2569),
                            EditionNumber = 4,
                            EditionYear = 2020,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2570),
                            Name = "Beni Kim Öldürdü?",
                            PageCount = 330,
                            Price = 247m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "beni-kim-oldurdu"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2574),
                            EditionNumber = 1,
                            EditionYear = 2022,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2609),
                            Name = "Zihin Kütüphanesi",
                            PageCount = 240,
                            Price = 300m,
                            Stock = 0,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "zihin-kutuphanesi"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2626),
                            EditionNumber = 11,
                            EditionYear = 2019,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2627),
                            Name = "Yeni Bir Yaşam",
                            PageCount = 400,
                            Price = 166m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "yeni-bir-yasam"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2631),
                            EditionNumber = 12,
                            EditionYear = 2020,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2632),
                            Name = "Gecenin Kraliçesi",
                            PageCount = 97,
                            Price = 19m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "gecenin-kralicesi"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2636),
                            EditionNumber = 10,
                            EditionYear = 2020,
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(2637),
                            Name = "Efendi Uyanıyor",
                            PageCount = 125,
                            Price = 75m,
                            Stock = 10,
                            Summary = "Nereden Gelir?\r\nYaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            Url = "efendi-uyaniyor"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 6
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "8754f846-65a8-40ce-959e-a14b262c6b18"
                        },
                        new
                        {
                            Id = 2,
                            UserId = "e322c6d4-0f25-4427-8c27-33d6c6825f9b"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7026),
                            Description = "Edebiyat türü burada",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7035),
                            Name = "Edebiyat",
                            Url = "edebiyat"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7040),
                            Description = "Başvuru kitapları burada",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7041),
                            Name = "Başvuru",
                            Url = "basvuru"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7043),
                            Description = "Çocuk kitapları burada",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7044),
                            Name = "Çocuk",
                            Url = "cocuk"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7046),
                            Description = "Ders kitapları burada",
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 809, DateTimeKind.Local).AddTicks(7047),
                            Name = "Ders Kitabı",
                            Url = "ders-kitabi"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "eb88ba80-93b4-4f9e-8653-ef3a9d874f73",
                            Description = "Yöneticiler",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "bc50fa52-b694-45a2-846b-7dd350e8f218",
                            Description = "Kullanıcılar",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8754f846-65a8-40ce-959e-a14b262c6b18",
                            AccessFailedCount = 0,
                            Address = "Halilpaşa Konağı Ap. No:18 Beşiktaş",
                            City = "İstanbul",
                            ConcurrencyStamp = "610cc00c-f9a1-4277-a4dd-28eabe1a07ab",
                            DateOfBirth = new DateTime(1985, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "deniz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Deniz",
                            Gender = "Erkek",
                            LastName = "Kartal",
                            LockoutEnabled = false,
                            NormalizedEmail = "DENIZ@GMAIL.COM",
                            NormalizedName = "DENIZKARTAL",
                            NormalizedUserName = "DENIZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEGzv698JcGyaBqyWlv6n4h0m3XLfkNCp0GGercIdj2yvFPYrwTSBhKLYV/02znYnnw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e0cf719c-85b7-4e69-af05-e7be88b04af9",
                            TwoFactorEnabled = false,
                            UserName = "deniz"
                        },
                        new
                        {
                            Id = "e322c6d4-0f25-4427-8c27-33d6c6825f9b",
                            AccessFailedCount = 0,
                            Address = "Sinanpaşa Cd Halime Hanım Ap. No:1 D:5 Kadıköy",
                            City = "İstanbul",
                            ConcurrencyStamp = "a4374b94-5741-4d81-9531-00d6cc16b9f9",
                            DateOfBirth = new DateTime(1989, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "selin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Selin",
                            Gender = "Kadın",
                            LastName = "Kanarya",
                            LockoutEnabled = false,
                            NormalizedEmail = "SELIN@GMAIL.COM",
                            NormalizedName = "SELINKANARYA",
                            NormalizedUserName = "SELIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEC6cMmZhn9JScCt4tA9l+S96lEjOyxNTLZqGB3bqgvT1Ie/tmlUvittxNIJr6tamAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0701d905-6d22-4bf6-8a2b-421301996a58",
                            TwoFactorEnabled = false,
                            UserName = "selin"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1102),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1112),
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1115),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1116),
                            Url = "2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1118),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1119),
                            Url = "3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1121),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1122),
                            Url = "4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1124),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1124),
                            Url = "5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1126),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1127),
                            Url = "6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1129),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1130),
                            Url = "7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1132),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1133),
                            Url = "8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1134),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1135),
                            Url = "9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1137),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1138),
                            Url = "10.jpg"
                        },
                        new
                        {
                            Id = 11,
                            BookId = 11,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1140),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1140),
                            Url = "11.jpg"
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1142),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1143),
                            Url = "12.jpg"
                        },
                        new
                        {
                            Id = 13,
                            BookId = 1,
                            CreatedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1145),
                            IsApproved = true,
                            ModifiedDate = new DateTime(2023, 4, 24, 16, 10, 54, 810, DateTimeKind.Local).AddTicks(1146),
                            Url = "222.jpg"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8754f846-65a8-40ce-959e-a14b262c6b18",
                            RoleId = "eb88ba80-93b4-4f9e-8653-ef3a9d874f73"
                        },
                        new
                        {
                            UserId = "e322c6d4-0f25-4427-8c27-33d6c6825f9b",
                            RoleId = "bc50fa52-b694-45a2-846b-7dd350e8f218"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.BookAuthor", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApp.Entity.Concrete.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.BookCategory", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApp.Entity.Concrete.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Cart", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.CartItem", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApp.Entity.Concrete.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Image", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Book", "Book")
                        .WithMany("Images")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Order", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.OrderItem", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApp.Entity.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
